name: update-offsets
on:
  schedule:
    - cron: "5 0 * * *"
jobs:
  updates-offsets:
    runs-on: ubuntu-latest
    steps:
      - name: Hit endpoint
        env:
          SECRET: ${{ secrets.ACTIONS_SECRET }}
        run: |
          curl "https://www.itsfiveoclocksomewhere.beer/api/updateOffsets?secret=$SECRET"
